export enum AppIcon {
  Dialpad = 'dialpad',
  Delete = 'delete',
  List = 'list',
  Forward = 'forward',
  PowerSettingsNew = 'power_settings_new',
  Edit = 'edit',
  Add = 'add',
  ContentCopy = 'content_copy',
  Code = 'code',
  Lock = 'lock',
  Password = 'password',
  Undo = 'undo',
  Unlock = 'lock_open',
  Cancel = 'highlight_off',
  Users = 'people',
  Trips = 'hiking',
  AssignUser = 'person_add',
  Payments = 'payments'
}
